#ifndef EB_GRAPHICS_ENUMS_H
#define EB_GRAPHICS_ENUMS_H

#include <GL/glew.h>

namespace eb {

enum BufferType {
    ARRAY_BUFFER = GL_ARRAY_BUFFER,
    ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER,
    SHADER_STORAGE_BUFFER = GL_SHADER_STORAGE_BUFFER,
    UNIFORM_BUFFER = GL_UNIFORM_BUFFER
};

enum UsageType { STATIC = GL_STATIC_DRAW, DYNAMIC = GL_DYNAMIC_DRAW, STREAM = GL_STREAM_DRAW };

enum PrimitiveType { TRIANGLES = GL_TRIANGLES, LINES = GL_LINES };

} // namespace eb

#endif // EB_GRAPHICS_ENUMS_H
